### ISSUE TITLE
Undefined variable $response -  Konekt\Factureaza\Endpoints\Client L72

### ISSUE THREAD

**Issue by lucionescu** [artkonekt/factureaza-sdk#1]
Hi!
When something goes wrong, this line (https://github.com/artkonekt/factureaza-sdk/blob/master/src/Endpoints/Clients.php#L72) throws a PHP exception.

The response needs to be available at that point somehow.

Thank you!

**Comment by fulopattila122** [comment]
Thanks for pointing this out. Can you give me an example when this happens? That would help improving the error handling mechanism

**Comment by lucionescu** [comment]
I think we have to take into account the logic in the catch block. Since we have a condition there, any other exception case that doesn't check the condition will fail because $response won't be available at the return point.
I cannot provide an example for the moment, but it seems that the logic only needs to be "error proof" in other cases as well.

LE: It happened while running a test. For now, the error no longer appears.

**Comment by fulopattila122** [comment]
Yeah, it makes sense :+1:
I keep this issue open, and we'll return to it soon for an improved error handling

**Comment by fulopattila122** [comment]
With the latest release (v1.6.0), error handling has improved. Now, all non-successful responses will throw a `FactureazaException` or a descendant exception containing the status code and the error message from the API.

In 404 situations, however, the SDK still doesn't throw an exception but simply returns `NULL`, as until now.
